[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sequence/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
